name: CI

on:
  push:
    branches:
      - master

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Rebase next against master
        env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/xing/hops.git
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git fetch origin master
          git fetch origin next
          git checkout -b next origin/next
          git rebase origin/master
          git push --force-with-lease
